version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Uke 39\StudentBloggAPI\Dockerfile
    ports:
    - 8080:80
    networks:
    - studentblogg-nett

    depends_on:
    - db

  db:
    container_name: studentblogg-db
    image: abdul80/stud-db
    # build:
    #    dockerfile: Dockerfile
    #    context: Docker\MySQL

    volumes:
    - studentblogg-vol:/var/lib/mysql
    ports:
    - 4444:3306
    networks:
    - studentblogg-nett

volumes:
  studentblogg-vol:   

networks:
  studentblogg-nett:
    driver: bridge  